### ISSUE TITLE
Numpy 1.17 Prefers random.Generator Instead of random.RandomState

### ISSUE THREAD

**Issue by daniel-de-vries** [OpenMDAO/OpenMDAO#1087]
In Numpy 1.17 random.Generator is preferred over using random.RandomState. RandomState is considered a legacy, backwards compatibility feature and it is frozen. According to the [docs](https://docs.scipy.org/doc/numpy/reference/random/legacy.html#legacy): "This class should only be used if it is essential to have randoms that are identical to what would have been produced by previous versions of NumPy." However, in OpenMDAO RandomState is used in several places (like the `SimpleGADriver`).

In the setup.py Numpy is listed simply as `'numpy'`. This means no version is preferred by OpenMDAO. Is there a reason not to require 1.17+?

**Comment by Kenneth-T-Moore** [comment]
I can't think of any reason we aren't using 1.17, except to not inconvenience current users.  Maybe we should consider bumping the numpy requirement up to 1.17 when we release 3.0, in which we will be dropping python 2 support.  We could revisit the numpy random number generation then too.

**Comment by Kenneth-T-Moore** [comment]
I looked into the specific issue a little bit more. OpenMDAO currently doesn't create or use RandomState, but it allows one to be specified so that it can be passed into pyDOE2.lhs. And even that is just an undocumented private attribute that is used to make sure our tests are reproducible.  

We decided for 3.0 not to require any particular version of numpy or scipy, but we are bumping up our testing to cover the more recent versions.
