### ISSUE TITLE
Clarification of InterpND and option to flatten output

### ISSUE THREAD

**Issue by sschnulo** [OpenMDAO/OpenMDAO#1357]
### Summary of Issue

Change 'points' option to 'x_cp' and give option to flatten output.

### Issue Type

- [ ] Bug
- [ x] Enhancement  

### Description

In InterpND, two options are `points` and `x_interp`. Proposed changing `points` to `x_cp` to stay consistent with the other options and SplineComp.

It would also be helpful to have an option to flatten the output.

### Example

N/A

### Environment

N/A

**Comment by Kenneth-T-Moore** [comment]
We used `points` for the control points because InterpND has two uses: 1) as an interpolating spline, like Splinecomp, and 2) as a table interpolator like StructuredMetaModel.  I think calling the table point locations "control points" or x_cp might lead to confusion when people use the interpND like that.

For the 'flatten' option, isn't it just as easy to take the result from `y = interp.evaluate_spline(y_cp)` and just do `y = y.flatten()`? (rather than adding an option).

Just to verify though, does the answer have extra dimensions that it shouldn't have? Maybe this is actually a bug.
