### ISSUE TITLE
Interp cache

### ISSUE THREAD

**Issue by achase90** [OpenMDAO/OpenMDAO#1620]
I wanted to check my understanding of this code - does this not cache and re-use the interpolant? We're having runtime issues and I think building and caching the interpolant would reduce runtime significantly.

https://github.com/OpenMDAO/OpenMDAO/blob/1f1e9e81810848a1c2b8e35eaeff6b94af9efc5d/openmdao/components/interp_util/interp_scipy.py#L264

**Comment by JustinSGray** [comment]
I don't see any caching in there. We know our interpolation stuff is a bit slow. You can speed things up by choosing a faster fitting algorithm. Try `scipy_cubic` or `slinear`. 

Are you using the interps directly? or via the StructuredMetaModel comp? We were just talking about adding some caching to the StructuredMetaModelComp. You can check out Issue #1606 to see my thoughts on that. In this one it was more of a runtime cache though. 

I suspect you're talking about caching to a file so that future runs will be more efficient?

**Comment by achase90** [comment]
We're using "MetaModelStructuredComp".

We're mainly thinking about caching during problem runtime so that future calls don't rebuild the interpolant, not a file cache for some future analysis.

Your thoughts in #1606 seem like they'd be great. I was even thinking more basic which might be quicker to implement:

In setup:
`self.interp = None
`

In compute:
```
if self.interp is None:
    self.interp = *build interp*
vals = self.interp(args)
```

I think your method in #1606 could sit on top of this approach.

**Comment by robfalck** [comment]
Per Justin's response, in my experience the interpolant "cubic" is a few times faster than "scipy_cubic," but we're looking to implement caching soon.

**Comment by JustinSGray** [comment]
@achase90 We're starting to look into the issue of caching now. We're looking at our own models to see if there is significant time to be saved here or not. 

There are two potential issues: 
1) The n-dimentional interpolation algorithm might not actually be that easy to cache. We need to dig a bit deeper here ... but its possible our interpolation method has sacrificed speed/cachability for flexibility. In this case, we might look into offering a faster interpolation scheme that is limited to 2 or 3 dimensions. 

2) In our testing on some dymos problems, we didn't see the MetaModel compute costs to be that signficiant. Could you provide us with a sample model that led you to examine the performance of MetaModelStructured?

**Comment by hschilling** [comment]
We did some profiling on models we thought might show excessive time in the interpolation code. We used cprofile with snakeviz to do the profiling and visualization.

1. dymos test_ex_min_time_climb.py script.

In the call to `min_time_climb` you can change the value of num_seg. We tried two values, 12 and 36.

For  num_seg = 12, interpolation only took 1/10 of the time
For num_seg = 36, it was even less. Just 1/20 of the time

2. pyCycle N3_MDP_Opt.py script

The metamodel `compute` only took 10 seconds in an 850 second run.

So we have not seen any examples of interpolation taking up a lot of a run’s time.

Also, just some more details on how interpolation is done in OpenMDAO. The issue is that the interpolation algorithm involves a lot of separate interpolation steps because we are using 1D interpolation for higher dimension interpolation and there is some code to do a linear solve at each level in order to assure continuous 2nd derivatives. See the section `Higher Order for Accuracy` in http://www.it.uom.gr/teaching/linearalgebra/NumericalRecipiesInC/c3-6.pdf
