### ISSUE TITLE
Refactor of complex-step vectors to save memory usage

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1767]
### Summary of Issue

Currently we allocate a complete separate array for complex values and swap it in when needed. This is wasteful though, and we can do a minor refactor to save the extra memory  

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM #30 (related to this POEM, but not the API changes for the POEM. Just an internal refactor as part of it)

### Description

Numpy allows you to create separate views into the real and complex parts of a complex array. So we don't need to allocate a separate real array when `force_alloc_complex` is on. Instead, we can just assign the view to the real part of that array. 

This will save roughly 33% of memory usage in complex step mode. It should be measurable since we have to allocate memory for both the output and the residual vectors. 

### Example

Different options for making the views: 
`myview = arr.real[start:stop]`

```
>>> a1 = np.ones(3, dtype=complex)
>>> r1 = a1.real 
>>> c1 = a1.imag
>>> r1[0] = 2
>>> a1 
array([2.+0.j, 1.+0.j, 1.+0.j])
```

**Comment by naylor-b** [comment]
Instead of creating view dicts for real and complex views, we could just create one view which is either real or complex, and then either return .real of it if complex step is not active or just the view itself if complex step is active.  So  inside the vector,   `self._views[name] = arr[start:stop]`  and then just return  `self._views[name].real`  or `self._views[name]` depending on complex step status.  That way we only need one views dict instead of two, and we don't have to swap the dicts back and forth when we turn complex step on and off.
