### ISSUE TITLE
Allow users to mark variables as constants in exec-comp

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1774]
For example, the input vector for the following: `ExecComp('x = a + b', a={'val': 6, 'input':False})`,
would contain only 'b'.  'a' would be treated as an internal constant attribute.  Specifying 'input' of False without specifying 'val' would be an error.
The default value of 'input' will be True.

**Comment by robfalck** [comment]
We can make this syntax more compact if we just allow constants to be passed in without dictionaries.

```
ExecComp('x = a + b', a=6)
```

Is there a more concrete use-case for this?
Why not just edit the calculation string at that point?

**Comment by naylor-b** [comment]
We already allow values to be set without a dictionary, so using that syntax doesn't tell us what we need to know, i.e., should 'a' be treated as a constant with value 6 or should it be an input to the component with a starting value of 6.

**Comment by naylor-b** [comment]
I do think the original syntax I presented could be improved.  We could either do something like `ExecComp('x = a + b', a={'val': 6, 'constant':True})` or maybe `ExecComp('x = a + b', a=6, constants=['a'])`

**Comment by naylor-b** [comment]
In terms of use cases, the main one I can think of would be the case where the equation would contain a large constant matrix and you wouldn't want to make that an input because it would result in unnecessary data transfers as well as creating larger vectors and jacobians that would be necessary.  I don't anticipate that this would be a common use case and so I don't think this is a very high priority story.
