### ISSUE TITLE
Produce error for a knowably unenforcible constraint or unnecessary design variable

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#1886]
### Summary of Issue

OpenMDAO drivers should produce an error if a constraint is not impacted by the design variables.

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

The first example below contains a constraint (parab.z) that is satisfied, but cannot be impacted by the design variables.  
This results in behavior that is inconsistent across different optimizers.  
- SNOPT and IPOPT successfully optimize it, but will fail if the constraint is specified as linear.
- SLSQP fails to find the correct answer

The OpenMDAO driver class should check for zero rows in the total jacobian and produce an error along the lines of

```Constraint {constrant_path} cannot be impacted by the design variables of the problem. ```
or
```Objective {objective_path} cannot be impacted by the design variables of the problem. ```

Rather than checking for exact zeros, OpenMDAO should probably check if the max value in a row is below some small threshold.

We should experiment with checking this condition at each iteration in the optimization, should the optimizer work itself into "flat" region of the search space.  If it proves to be too expensive, it should at least be checked at the start of optimization.

On the other hand, OpenMDAO should also warn the user if a design variable that has no impact on the problem.
This is shown in the second example below, where design variable `g` doesn't impact the solution.

```Design variable {desvar_path} has no impact on the constraints or objective. ```

Since this change may break user code, add a new driver option `'singular_jac_behavior'` that must be one of `'error'` (the default), `'warn'`, or `'ignore'`.

### Example

```
    def test_opt_jac_zero_row(self):
        import openmdao.api as om

        # We'll use the component that was defined in the last tutorial
        from openmdao.test_suite.components.paraboloid import Paraboloid

        # build the model
        prob = om.Problem()
        prob.model.add_subsystem('parab',
                                 om.ExecComp(['f_xy = (x-3.0)**2 + x*y + (y+4.0)**2 - 3.0',
                                              'z = 12.0'],),
                                 promotes_inputs=['x', 'y'])

        # define the component whose output will be constrained
        prob.model.add_subsystem('const', om.ExecComp('g = x + y'), promotes_inputs=['x', 'y'])

        # Design variables 'x' and 'y' span components, so we need to provide a common initial
        # value for them.
        prob.model.set_input_defaults('x', 3.0)
        prob.model.set_input_defaults('y', -4.0)

        # setup the optimization
        prob.driver = om.pyOptSparseDriver()
        prob.driver.options['optimizer'] = 'SLSQP'
        # prob.driver.opt_settings['iSumm'] = 6  # for SNOPT
        # prob.driver.opt_settings['print_level'] = 5  # for IPOPT

        prob.model.add_design_var('x', lower=-50, upper=50)
        prob.model.add_design_var('y', lower=-50, upper=50)
        prob.model.add_objective('parab.f_xy')

        # to add the constraint to the model
        prob.model.add_constraint('const.g', lower=0, upper=10.)
        prob.model.add_constraint('parab.z', equals=12.)

        prob.setup()
        prob.run_driver()

        # minimum value
        assert_near_equal(prob.get_val('parab.f_xy'), -27., 1e-6)

        # location of the minimum
        assert_near_equal(prob.get_val('x'), 7, 1e-4)
        assert_near_equal(prob.get_val('y'), -7, 1e-4)
```

An an example where design variable `z` does nothing.

```
    def test_opt_jac_zero_col(self):
        import openmdao.api as om

        # We'll use the component that was defined in the last tutorial
        from openmdao.test_suite.components.paraboloid import Paraboloid

        # build the model
        prob = om.Problem()
        prob.model.add_subsystem('parab',
                                 om.ExecComp(['f_xy = (x-3.0)**2 + x*y + (y+4.0)**2 - 3.0',
                                              'foo = 0.0 * z'],),
                                 promotes_inputs=['x', 'y', 'z'])

        # define the component whose output will be constrained
        prob.model.add_subsystem('const', om.ExecComp('g = x + y'), promotes_inputs=['x', 'y'])

        # Design variables 'x' and 'y' span components, so we need to provide a common initial
        # value for them.
        prob.model.set_input_defaults('x', 3.0)
        prob.model.set_input_defaults('y', -4.0)

        # setup the optimization
        prob.driver = om.pyOptSparseDriver()
        prob.driver.options['optimizer'] = 'SNOPT'
        # prob.driver.opt_settings['iSumm'] = 6
        # prob.driver.opt_settings['print_level'] = 5
        # prob.driver.declare_coloring()

        prob.model.add_design_var('x', lower=-50, upper=50)
        prob.model.add_design_var('y', lower=-50, upper=50)
        prob.model.add_design_var('z', lower=-50, upper=50)
        prob.model.add_objective('parab.f_xy')

        # to add the constraint to the model
        prob.model.add_constraint('const.g', lower=0, upper=10.)
        # prob.model.add_constraint('parab.foo', equals=0., linear=False)

        prob.setup()
        prob.run_driver()

        # minimum value
        assert_near_equal(prob.get_val('parab.f_xy'), -27., 1e-6)

        # location of the minimum
        assert_near_equal(prob.get_val('x'), 7, 1e-4)
        assert_near_equal(prob.get_val('y'), -7, 1e-4)
```

### Environment

OpenMDAO 3.6.1-dev

**Comment by JustinSGray** [comment]
This is a great start. Good tests! I have a few notes on additional requirements I think are important

Fundamentally, this test is checking for singularity in the total derivative Jacobians. Singularities can be caused by one of 4 things: 

1) A row of all zeros 
2) A column of all zeros 
3) Two (or more) rows that are linearly dependent (i.e. differ only by a constant factor) 
4) Two (or more) columns that are linearly dependent 

(1) and (2) are very cheap to check for. They are also the most likely mistake to happen. A zero row means a constraint that is not affected by any DV. A zero column means a DV that does not affect anything. A common cause of this problem is a missed connection, though in Dymos you can create them even without that.

(3) and (4) are much more expensive (because they require comparing every row/column to every other row/column).
It makes sense to me to do both checks at the initial condition of a problem. Most errors would show up at any condition, so the initial condition is as good as any to check at. checking (3) and (4) shouldn't be that expensive that we can't afford to do it in 95% of cases. There are some corner cases to be aware of, like distributed Jacobians (currently under development at GT) where (3) and (4) are not practical though. So ultimately. it probably needs to be an optional check. 

I suggest two options added to drivers with derivatives: `check_zero_row_col` and `check_linear_dependent_row_col`. These would control if the check is done **at the initial condition before optimization starts`. Both would default to true. 
A third option `singular_jac_error` should also default to true, and would control if it's an error or a warning. 

It's possible that user mistakes in the component code (e.g. weird if conditions that might make some output become constant when some input crosses a threshold). If that happened, the singularity might not show up at the initial condition, but only later on during some middle iteration. I do not think we should check for this during optimization. Its too expensive to do (3) and (4) all the time, and checking half the conditions doesn't seem idea. Plus, one time overhead at startup seems less offensive than constant overhead. To handle this situation, I propose that we add a utility that can review a set of cases, pull out the jacobians, and run the check on them. I think that gives all the functionality we need. 

Finally, I think we should consider including this check in the `scaling_report` feature. Though this would technically be non scaling related data, we already have the nice visualization of the Jacobian there and can easily show them which rows/cols are singular. 

Lastly, given how much I just wrote about this... probably worth a POEM
