### ISSUE TITLE
Look into excess scaling vector allocation 

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1887]
### Summary of Issue

We are potentially allocating memory for scaler/adder for both fwd and reverse modes

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

From discussion with users at DLR, they noted that in OpenMDAO V2.10 we were allocating separate vectors for fwd and rev modes. Im not sure if we are currently still doing this or not, but if so we don't need to. 

We can multiply by the scalers in fwd and divide by them in reverse mode. That will save 2 additional vector allocations. 

Investigate if we are still doing this un-needed allocation and update if necessary.

**Comment by Kenneth-T-Moore** [comment]
Whenever we have a `ref` or `ref0` defined on an output, we store 4 scaling vectors that are full vector width. They are:

    adder, scaler :  physical -> scaled
    adder, scaler :  scaled -> physical

My recollection is that we did it this way so that we weren't dividing a vector by a vector, which is much slower than multiplication. We scale or unscale before and after every call to Component API function. We also do this around certain other calculations internally, so this ends up happening many times and we need it to be efficient.

However, there is a trade-off between efficiency and memory usage, and maybe the user should decide which is important.

Some things we can do:

1. We only really need to allocate 3 vectors instead of 4 if we refactor this a little so that we can use the same adder for both directions. It's addition vs subtraction, which should be close in speed.

2. We are allocating adder when we only define ref0. That's 2 vectors of zeros we don't need.
(Note, when we have no scaling at all, we don't define any scaling vectors, so that's good.)

3. A performance mode flag on the problem to choose: 
  a) allocate one adder with multiply / divide (slower but less memory allocated); 
  b) allocate two vectors for adder with multiply / multiply (faster but more memory).
