### ISSUE TITLE
Make MPI/Petsc Warnings less annoying/confusing for users

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1917]
### Summary of Issue

The warning: 

`Unable to import petsc4py. Parallel processing unavailable` 

confuses many users (or at least they find it annoying). Its not clear where the warnings come from (i.e. which package). They could be made more clear, and also be changed from warnings to errors that only get raised when some functionality is accessed that won't work without petsc4py or MPI4py. 

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM # N/A

### Description

The warnings are thrown here: 

https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/core/total_jac.py#L30-L36

https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/utils/mpi.py#L66-L77

https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/solvers/linear/petsc_ksp.py#L19-L26

You basically get all three any time you import OpenMDAO, regardless of whether or not you're using any mpi/petsc stuff. There should be a less annoying way to do this... 

Change warnings to errors, and raise them only when the functionality is accessed (rather than just imported)? 

Im open to other suggestions, but we need to clean this up somehow.

**Comment by tadkollar** [comment]
The difficulty comes from autodetecting whether the user _intends_ to use MPI - there's not a reliable way to do it. So to make it straightforward, we could have users positively indicate when they want to do a parallel run and attempt it only then.

The `OPENMDAO_REQUIRE_MPI` env variable is already supported, but if unset, the current default is to autodetect. A quick way to solve the problem is to change the default to disable MPI. Users would have to set `OPENMDAO_REQUIRE_MPI=1` to run in parallel. Most users are probably not using MPI, so it seems reasonable.

We could also add a `--parallel` command line option, in addition to or instead of the env variable.

**Comment by JustinSGray** [comment]
Can you give a situation when its ambiguous? It seems clear to me. 

For instance: If they import solvers from petsc, and you don't have petsc... give an error. Otherwise stay silent. 

If they try to use a distributed vector... and you don't have mpi/petsc then throw an error. Is there a time when you try to use a distributed vector even though you're not running with mpiexec?

**Comment by tadkollar** [comment]
I'm concerned whether decisions happen before that point is reached, that may be based on whether MPI is available. For instance `from openmdao.utils.mpi import MPI` is used in 37 different non-test files in OM, and not all of them reference petsc or a distributed vector.

But maybe it's enough just to slightly alter the purpose of `OPENMDAO_REQUIRE_MPI` instead of relying on it to decide to import MPI - if it's set and MPI isn't available, the user will get an error immediately, and if not, they'll won't get an error until they try to use petsc/MPI. That way they have control over the behavior if it's important.

**Comment by JustinSGray** [comment]
I think we've agreed (POEM 044) to control the errors/warnings via some other means. 

I had a quick look at a few of the uses of the MPI in the various files, and in the mpi.py itself. 

`from openmdao.utils.mpi import MPI` gives None if the import fails. So we're effectively already handling the situation gracefully here. I really think the warnings are just not necessary as long as we give clear errors when you try to access the MPI object. 

The warnings are confusing enough to users, that I'd even prefer to have a slightly less clear error for parallel users in favor of not confusing the serial ones. 

I am ok with the proposed modification of OPENMDAO_REQUIRE_MPI, so that be default users won't see a warning here.
