### ISSUE TITLE
Output reference interferes with total derivatives computation

### ISSUE THREAD

**Issue by GuillaumeFiorello** [OpenMDAO/OpenMDAO#2119]
### Summary of Issue

Declaring a reference level for an output variable of a component with multiple design parameters as inputs interferes with the total derivatives analytic computation of a model having other components after.

### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Hello!

I work with OpenMDAO as part of a student project. During the bug solving process, I stumbled upon this issue, and I don't know if it qualifies as a bug or if I misunderstood the intended behaviour of OpenMDAO.

The simplest model architecture presenting the issue has the following pattern:
- a component with two inputs and one output (comp 1)
                    directly linked to
-  a component with one input and one output (comp 2)

We are trying to optimize the output of component 2 with respect to BOTH inputs of component 1 (for some reasons, the issue doesn't happen if there is only one design variable). The output of component 1 is the input of component 2.

Everything works fine when no reference level is declared, but if a reference level (let's call it ref) other than 1 is declared for the output of component 1, it changes the total derivative analytic computation by a factor ~ref**2. (e.g. if output reference level is 10, all the analytic total derivatives computed involving that output will be 100-folded). 

This is revealed by calling the method 'check_totals' of the Problem class after the problem is solved.

### Example

See test script here : https://github.com/GuillaumeFiorello/OpenMDAO_Issue2119
Change the value of the 'ref' variable at the beginning of the 'Components definition' section

### Environment

Operating System: Ubuntu 20.04.2

Python environment: Python 3.9.1

Packages: OpenMDAO 3.9.1

**Comment by GuillaumeFiorello** [comment]
Sorry, wrong link to the test script 
Here is the updated one : 
https://github.com/GuillaumeFiorello/OpenMDAO_Issue2119

**Comment by JustinSGray** [comment]
this does look like a legit bug. We'll get it sorted out quickly. I suspect that its just a bug in the printing of the check_partials code. 

We haven't run into this ourselves because the ref values for outputs variables are not used very often. Their effect is a bit mathematically esoteric and the use case for them is mostly limited to correcting numerical ill conditioning problems in the partial derivative jacobian. 

I would make a guess that you were attempting to use the ref values to get the scaling right for an optimizer? that general use case is the most common application of `ref`, but you shouldn't add it to the output itself. Rather you should add the `ref` argument to the `add_des_var` call on driver. I suppose that is a bit confusing, since they are both `ref`... 

In the even that you really did mean to scale the partial derivative jacobian though, I agree this is a bug and we'll get it sorted.

**Comment by GuillaumeFiorello** [comment]
Hello and thank you for your answer,

I was attempting to use the ref values to get the scaling right for an optimization process, but not for a design variable. In the real problem I'm working on, this scaling is done on an unremarkable coupling variable. I do not know if scaling it could help the MDO to converge, but I thought it could not be detrimental (bug aside). That's why I attempted to set a ref level outside of the add_des_var method.
