### ISSUE TITLE
Experiment with using OpenMDAO in a dashboard environment.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2223]
### Summary of Issue

Make a simple dashboard in one or more available environments (`tableau`, `dash`, `streamlit`, etc) to see if there are any hang-ups in using OpenMDAO in this manner.

### Issue Type

- [x] Task
- [ ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

With dashboard environments like `tableau` becoming popular, we should make a small example of one that uses OpenMDAO.  We mainly want to see if there is anything that makes it difficult to use OpenMDAO in this way.

### Example

N/A

### Environment

N/A

**Comment by andrewellis55** [comment]
I've been been building a Dash application centered around openmdao for about 2 years now. It's closed source but I'd be happy to have a chat if you'd like some insight on my experiences with it.

In my experience the main hang-up is passing an openmdao problem (or model or component) between callbacks, as in order to do this, the relevant information needs to be either pickled or converted to json. Say for example we have one button that runs the driver for a problem and another that tries to use get_val on a problem to return some information, the user may run into the issue of how to pass the problem between callbacks. There are some workarounds for sure, but generally speaking it doesn't seem trivial.
