### ISSUE TITLE
Issue on reports

### ISSUE THREAD

**Issue by kasia129** [OpenMDAO/OpenMDAO#2641]
I am trying to disable any reports, to be able to benchmark the runtime of my problem. Despite the OPENMDAO_REPORTS variable being set to none, the n2 report is being created.

`os.environ.get('OPENMDAO_REPORTS')`

gives 
> None

How do I prevent the report from being created?

**Comment by robfalck** [comment]
Allowing `"none"` to be considered as a "falsy" environment variable is leading to this confusion I think.  If the environment variable is not set, `os.environ.get('OPENMDAO_REPORTS')` will return the Python `None` object.  Note the upper-case N.

Otherwise, the environment variable will always return its string value.  In this case, explicitly setting the environment variable to `0` or `false` or `none` (note the lower-case n) should disable the reports.

See https://openmdao.org/newdocs/versions/latest/features/reports/reports_system.html?highlight=openmdao_reports#controlling-reporting-using-an-environment-variable for more information.

**Comment by kasia129** [comment]
Thank you. I am sorry, I was not very clear. I did try exactly what have suggested:

```
os.environ['OPENMDAO_REPORTS'] = 'none'
print(os.environ.get('OPENMDAO_REPORTS'))
```

This did print  `none`, however, the n2 report has still been created.

I was able to disable the reports by setting the reports argument to Problem to False:

`prob = om.Problem(model=MDA(),reports=False)`

Should not both ways work the same way?

**Comment by robfalck** [comment]
They should, I'll take a look.

**Comment by robfalck** [comment]
This is in fact an issue.  The documentation states  `OPENMDAO_REPORTS=none` should have the effect of turning off all reports, but currently the list that causes that behavior is one of:

`OPENMDAO_REPORTS=0`
`OPENMDAO_REPORTS=false`
`OPENMDAO_REPORTS=no`
`OPENMDAO_REPORTS=off`

We'll address this, in the meantime use one of the options above.
