### ISSUE TITLE
Remove pyparsing as a standard dependency.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2693]
### Desired capability or behavior.

In the interest of removing the dependency burden on users, we should remove `pyparsing` from our standard dependencies and inform the user of how to install it when needed.

### Associated POEM

None

**Comment by swryan** [comment]
We currently require `Version` from [packaging ](https://pypi.org/project/packaging/)for our tests (71 occurrences in various tests. used to test against different versions of `NumPy`, `SciPy` and `pyOptSparse`).

This in turn will give us [pyparsing](https://pypi.org/project/pyparsing/):
```
pyparsing==3.0.9
  - packaging==21.3 [requires: pyparsing>=2.0.2,!=3.0.5]
    - openmdao==3.21.1.dev0 [requires: packaging]
```

In order to remove the `pyparsing` dependency, we will also have to either disable any tests that use `Version` or find a different solution for checking versions.

Do we want to do this?

**Comment by swryan** [comment]
I'll move [packaging ](https://pypi.org/project/packaging/) to the `[test]` extras, and then add `@skipUnless` to the `Version` tests
