### ISSUE TITLE
`set_input_defaults` / `add_input` consistency

### ISSUE THREAD

**Issue by relf** [OpenMDAO/OpenMDAO#2786]
### Description

I would have expected `input_set_defaults()` to have the same parameters handling as `add_input()`.

In `add_input()`, the value and the shape of a variable are made compatible with `ensure_compatible()`. 
But when using `set_input_defaults()`, the value `val` takes precedence over the shape `src_shape` (why not `shape` name?).
It gives a warning if `val` and `shape` are compatible which is not really needed. 
It gives an error in the special case where `shape` and `val` could be made compatible like in `add_input()` (see example below).

### Example

```python
import openmdao.api as om
import numpy as np

class Paraboloid(om.ExplicitComponent):
    def setup(self):
        self.add_input('x', val=0.0, shape=(2,))
        self.add_input('y', val=0.0)

        self.add_output('f_xy', val=0.0)

    def compute(self, inputs, outputs):
        x = inputs['x']
        y = inputs['y']
        outputs['f_xy'] = (x[0] - 3.0)**2 + x[0] * y + (y + 4.0)**2 - 3.0

prob = om.Problem()
model = prob.model

model.add_subsystem('comp', Paraboloid(), promotes=['*'])

model.add_design_var('x', lower=-10, upper=10)
model.add_design_var('y', lower=-10, upper=10)
model.add_objective('f_xy')

# model.set_input_defaults('x', val=[1.0, 1.0], src_shape=(2,))
# -> WARNING PromotionWarning:<class Group>: value was set in set_input_defaults, so ignoring value (2,) of src_shape
model.set_input_defaults('x', val=1.0, src_shape=(2,))  
# -> ERROR <model> <class Group>: The source and target shapes do not match or are ambiguous for the connection '_auto_ivc.v0' to 'comp.x'. The source shape is (1,) but the target shape is (2,).

prob.setup()

prob.run_model()
prob.cleanup()
```

### OpenMDAO Version

3.23.0

**Comment by robfalck** [comment]
The reason we use `src_shape` and not `shape` here, is because `set_input_defaults` is meant to be used for disambiguation when OpenMDAO is making automatic IndepVarComps (AutoIVCs) for outputting the unconnected inputs.

You're not changing the shape of the input on the component itself, but rather telling it how large the AutoIVC output which provides its value is.  There are situations where we may be using src indices so that some components pull only certain indices from a vector-sized input from the same autoIVC.  OpenMDAO needs to know the full shape to allocate that AutoIVC output, hence the `src_shape`.

In your case, setting val to `np.ones(2)` should accomplish what you want.  We may be able to allow both `val` and `src_shape` to be set though, I need to think about the impacts from that.

**Comment by relf** [comment]
Thanks. 

Sure, I can workaround this problem. My point was more on the opportunity to have the same behaviour as in `add_input` or maybe I should have said `add_output`, because my understanding of `set_input_defaults` is that it ends up being the equivalent of manually creating an `IndepVarComp` with an `add_output(<name>, val=<val>, shape=<src_shape>)`. Hence having the same API would be more consistent from a user standpoint. 

(name nitpicking: why the rational for `src_shape` does not apply to `val`? `src_val`? )

**Comment by robfalck** [comment]
I am looking to see if val and src_shape can be made to work together

**Comment by robfalck** [comment]
I _think_ we can resolve this one by doing a `np.broadcast_to` from the val to the given src_shape.
In any case, doing this where val is a scalar to be broadcast to the entire input should be possible.
