### ISSUE TITLE
Issue with openmdao.surrogate_models.multifi_cokriging

### ISSUE THREAD

**Issue by mgisellef** [OpenMDAO/OpenMDAO#764]
Hi,

I am using co-Kriging from this library. I am modeling a 5 variable problem. Initially, I had 1400 low fidelity (LF) data and 500 high fidelity (HF) data. I was getting the error below. After I tried everything I reduced the number of samples to (500 LF and 250 HF)  and now it works. My guess is that the correlation matrix became ill-conditioned. 

  File "<ipython-input-109-8966c79b79e4>", line 1, in <module>
    runfile('C:/Users/gisellefernandez/Desktop/Dropbox/PhD/LaTeX/PhDThesis/GiselleThesis/Multi-fidelity-chapter/Fitting_NFEP/co-Kriging/OpenMDAO_NFEP_LF_HF.py', wdir='C:/Users/gisellefernandez/Desktop/Dropbox/PhD/LaTeX/PhDThesis/GiselleThesis/Multi-fidelity-chapter/Fitting_NFEP/co-Kriging')

  File "C:\Users\gisellefernandez\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\gisellefernandez\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/gisellefernandez/Desktop/Dropbox/PhD/LaTeX/PhDThesis/GiselleThesis/Multi-fidelity-chapter/Fitting_NFEP/co-Kriging/OpenMDAO_NFEP_LF_HF.py", line 99, in <module>
    mcok.predict(np.array([[0.8],[0.3],[0.4],[0.3],[0.9]]).T, eval_MSE = True)

  File "C:\Users\gisellefernandez\AppData\Local\Continuum\anaconda2\lib\site-packages\openmdao\surrogate_models\multifi_cokriging.py", line 642, in predict
    Ft = solve_triangular(C, F, lower=True)

  File "C:\Users\gisellefernandez\AppData\Local\Continuum\anaconda2\lib\site-packages\scipy\linalg\basic.py", line 286, in solve_triangular
    raise ValueError('expected square matrix')

ValueError: expected square matrix

**Comment by JustinSGray** [comment]
can you provide an actual test case that shows the problem here?

**Comment by mgisellef** [comment]
Sure, find it attached. The data files *NFEP.dat are the ones that are
giving the error. The data files *NFEP_short3.dat are the shortened ones
which work.

Regards,


*M. Giselle Fernandez*
Ph.D. Candidate - Research Assistant
Mechanical and Aerospace Engineering Department
University of Florida
https://sites.google.com/site/mariagisellefernandez/

**Comment by Kenneth-T-Moore** [comment]
I apologize for the late response. I have downloaded your code, and experimented with it, and you are correct that the correlation matrix has become ill-conditioned.   It is actually still ill-conditioned with the 500 point case as well, though `cholesky` can handle it because the ratio of the maximum to minimum singular value is below the ~1e16 threshold that determines positive definite-ness.   

I'm no expert in this area, but I played around with some different sampling strategies and found that a more uniform distribution of the training points (like a full factorial) gave a much lower condition number than a random spacing of points.   Not much you can do about the spacing when you have already run the points, but for your model, i did get it to work by removing the step where you scaled everything to lie on (0, 1).   I think that scaling may not be the right one to use with Kriging.  I usually see (X-Xmean)/Xstd, though using that on your model didn't make much difference in the condition number over the unscaled values, but it does change the prediction some..

I don't see a bug in openmdao here, though I will check to see if we need to rescale incomiing training and prediction datapoints.  We might also benefit from pulling over some of the other correlation functions from scikit-learn.

**Comment by robfalck** [comment]
This issues been quiet for a few months, closing.
