### ISSUE TITLE
Feature request: active-set constraint calculation disabling

### ISSUE THREAD

**Issue by jaredthomas68** [OpenMDAO/OpenMDAO#926]
We are still using OpenMDAO 1.7.4, but would like to move to OpenMDAO 2. We have not moved up to OpenMDAO 2 largely because active-set constraint calculation disabling is still not a part of OpenMDAO 2. 

This feature is important for our project since we deal with thousands of variables, most of which are unimportant at any given step. Active-set constraint calculation disabling provides us with significant speed-ups in solving our optimization problems.

**Comment by JustinSGray** [comment]
We can look at adding this to the development schedule for sure. This feature was originally developed for your purposes, IIRC. However, V2 has a large number of significant speed improvements over V1. The most important of which might be the DirectSolver and AssembledJacobian. We also have a new coloring algorithm that might be able to be used, if you can reduce the separation constraint from n2 to less with some pre-determination of which pairs can never intersect. 

Have you tried V2 at all yet? It might be worth doing a few tests to see if these new features make it worth switching even before we get the active set constraint stuff in there. The direct solver in particular makes it so that doing many linear solves for constraints longer fundamentally prohibitively expensive.

**Comment by robfalck** [comment]
@jaredthomas68 We understand that you've upgraded to OpenMDAO v2 without this feature, do you still consider this a necessary issue?

**Comment by jaredthomas68** [comment]
Thanks for following up. While I think it could still be helpful, I don't
consider it necessary.
