### ISSUE TITLE
BalanceComponent default "normalize" option randomly causes DirectSolver singular errors

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#948]
I was porting all my OpenConcept test cases over to my new solver ODE-based formulation and for some reason my Caravan test case just would not converge. I was getting 

> RuntimeError: Identical rows or columns found in jacobian in ''. Problem is underdetermined.

errors but only for certain combinations of wing area and MTOW which was odd to me. I followed the advice [here](http://openmdao.org/twodocs/versions/latest/features/debugging/newton_solver_not_converging.html?highlight=singular) but found no NaN / div 0 problems in the partial derivatives or output values.

It turns out that the problem was due to the normalize=True default of the BalanceComp I was using to set throttle. Problem immediately resolved and Newton converged normally when I turned that option to False. Because of the particular RHS value at the starting point, the sensitivity of the balance comp to the LHS was almost zero after normalization. 

The nonspecific error message (i.e. not identifying the component with the issue by name and component) exacerbated the debugging process.

Proposed resolution is one of the following:
- mention "near-zero partial derivatives in implicit components" as a possible cause of singular Jacobian convergence failures
- make normalize=False the default for BalanceComponent to avoid non-intuitive behavior

Suggestion:
- identify singular entries by name in the OpenMDAO namespace for all types of assembled jacobians. csc provides no info and Dense provides little info on where to isolate the problem in your model

**Comment by JustinSGray** [comment]
we can and will make the error msg more clear, at least by giving the full path to which solver is raising the error.

Which commit of OpenMDAO are you using (or which version at least). We did recently address some of these issues... but perhaps not this specific error msg.  

Im not sure about this one though: 
`make normalize=False the default for BalanceComponent to avoid non-intuitive behavior`

That normalization is there because in most cases it makes sense to divide by the right-hand side. There is code in there to make sure you that you don't divide by a number less than 1 (so if the RHS goes to 0, then you effectively don't normalize). 

So Im curious what situation caused the normalization to behave badly? In the vast majority of cases we've seen, dividing by RHS makes the residual more well behaved, not less. Can you construct a representative case (or at least describe a hypothetical one) where the normalization gets poorly defined? 

Regardless, we specifically added the option to turn it off for this reason. There are cases where you would not want to use it. I would suggest that maybe 
1) you should swap the LHS and RHS in your balance? 
2) maybe you need to use guess_nonlinear to get better initial values?

**Comment by bbrelje** [comment]
The balance component matches horizontal acceleration (m/s^2) [RHS] to zero acceleration [LHS]. I am not using a LHS multiplier. The partials of the residual wrt my RHS with normalization turned on is 16 orders of magnitude smaller than for the LHS. I can't explain that based on the formula for normalization in the current docs so maybe there is an implementation problem?

Following image is WITH normalization:
![image](https://user-images.githubusercontent.com/18647766/58683832-d9f3a800-832a-11e9-97ba-bcca61e91e55.png)

Next WITHOUT:
![image](https://user-images.githubusercontent.com/18647766/58683873-03accf00-832b-11e9-9ddc-0911f0f3d416.png)


When I built the first iteration of OpenConcept in 2.3.0 I don't think the normalization was being done. Since I wasn't using a multiplier it wasn't apparent to me that there was a mathematical difference between RHS and LHS [at that time](http://openmdao.org/twodocs/versions/2.3.0/features/building_blocks/components/balance_comp.html)

**Comment by JustinSGray** [comment]
We were doing some normalization[ in 2.3.0](https://github.com/OpenMDAO/OpenMDAO/blob/b715ec0dc87ad08e6169a4776dc146f2d05a1d14/openmdao/components/balance_comp.py#L166-L195) and that bit of code does not look like its changed [in 2.7.1](https://github.com/OpenMDAO/OpenMDAO/blob/b715ec0dc87ad08e6169a4776dc146f2d05a1d14/openmdao/components/balance_comp.py#L166-L195). However, the docs were incorrect in 2.3.0 since we didn't discuss the normalization. So the component code is the same...

Im guessing that we're now throwing an error for something that before we were just silently swallowing and you were able to power through it. 

Is your RHS explicitly set to 0 (either with an IVC output, or by passing `rhs_val=0` as an argument to add_balance)? If so, thats the region where the scaling is actually not just `rhs`, but rather 
(.25x^2+1) which looks like: 
![Uploading Screen Shot 2019-05-31 at 6.54.33 AM.png…](this)

So that scaling factor should have become exactly 1, if your RHS was actually exactly 0. So maybe we have a bug in our derivatives... could you use list_inputs to verify the value of LHS and RHS just before you compute those partials for the normalized calculation?

**Comment by robfalck** [comment]
This is the result of choosing the "wrong" input for the RHS/LHS.  We will address this more in documentation, and possibly see if we can check for this condition.
