### ISSUE TITLE
Many new warnings raised in 2.7.1

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#949]
The "check" function during setup raises the following new type of WARNING following the upgrade to 2.7:

> WARNING: Input 'analysis.v0v1.acmodel.OEW.totalempty.W_propeller' was explicitly connected in group 'analysis.v0v1.acmodel' as 'W_propeller', but was promoted up from groups ['analysis', 'analysis.v0v1.acmodel']

I do this all over the place in my models in OpenConcept so dozens/hundreds of warnings are now raised at check time. Is this type of connection functionality staged for deprecation? If so, why? If not, why the warning? What exactly is the danger here?

**Comment by JustinSGray** [comment]
To be clear, whats going on here is that you have a group `analysis.v0v1.acmodel`. In that group, you have promoted `analysis.v0v1.acmodel.OEW.totalempty.W_propeller` to be named `W_propeller`. 
Then in that group you have connected some variable (the error msg doesn't currently say which one, but we're going to fix that...) to W_propeller. The connected source variable is *not* promoted to the same name (hence the need for the connection at all). 

Then, later when you add `analysis.v0v1.acmodel` to some other group, you also promote `W_propeller` out of that group so it exists in `analysis.v0v1`

Here is the rub though. You have only promoted the *input* variable up to `analysis.v0v1`, but that input variable already has a connected source output down inside that group. So this promotion has accomplished nothing. You currently can not access the variable from the problem level as`analysis.v0v1.W_propeller`, since inputs are always addressed using their full path name (only outputs are addressed using promoted names).  Also, since it is already connected down inside `analysis.v0v1.acmodel`, you can't connect anything to it up form within `analysis.v0v1` either. 

I suspect what you really wanted to do was make that variable available at the higher level, so likely you should have also promoted the output source variable within `analysis.v0v1.acmodel` to also be `W_propeller` and then the warnings would all go away, and you could acctually access the variable as
`analysis.v0v1.W_propeller` from the problem level. 

This was a weird corner case we discovered ourselves recently when we did something similar in one of our own models and it caused confusion. We considered adding an error, but went with the warning because we wanted to avoid breaking peoples models. You're right though, if we're going to keep this warning we should mark the behavior for deprcation, and dis-allow it in a later version. 

If you agree that the promotion doesn't make sense, do you still think you need to do it all over your models? Despite the promotion not achieving anything (since the output side is not promoted as well), do you have an argument for why it should be allowed?

**Comment by naylor-b** [comment]
These warnings no longer appear as part of our default set of checks.   The check in question can still be performed, but only if the user explicitly requests it by adding ['promotions'] to the list of checks.  For example, prob.setup(check=['promotions']).
